const API = "http://localhost:3000";
const PLACEHOLDER = "https://placehold.co/400x250?text=Sin+imagen";
const user = JSON.parse(localStorage.getItem("user") || "null");
const token = localStorage.getItem("token");
if (!user || !["admin", "superadmin"].includes(user.rol)) window.location.href = "./login.html";
let productosGlobal = [];
window.logout = function () { localStorage.removeItem("user"); localStorage.removeItem("token"); window.location.href = "/pages/login.html"; };
async function cargarCategorias() { const res = await fetch(`${API}/categories`); const categorias = await res.json(); const options = categorias.map(c => `<option value="${c.id}">${c.nombre}</option>`).join(''); categoria.innerHTML = options; categoriaActualizar.innerHTML = options; }
async function cargarProductos() { const res = await fetch(`${API}/productos`); productosGlobal = await res.json(); listaProductos.innerHTML = productosGlobal.map(p => `<div class="card" data-id="${p.id}"><img src="${p.imagen || PLACEHOLDER}" onerror="this.onerror=null;this.src='${PLACEHOLDER}'"><div class="card-body"><h3>${p.nombre}</h3><p class="precio">$${Number(p.precio).toFixed(2)}</p><p>Stock: ${p.stock}</p><p>${p.category?.nombre || ''}</p><button class="btn-vender" data-id="${p.id}" ${p.stock < 1 ? 'disabled' : ''}>Vender 1 unidad</button></div></div>`).join('');
  document.querySelectorAll('.card').forEach(card => card.addEventListener('click', (e) => { if (e.target.classList.contains('btn-vender')) return; const p = productosGlobal.find(prod => prod.id == card.dataset.id); if (!p) return; idActualizar.value = p.id; nombreActualizar.value = p.nombre; precioActualizar.value = p.precio; stockActualizar.value = p.stock; imagenActualizar.value = p.imagen || ''; categoriaActualizar.value = p.categoryId; }));
  document.querySelectorAll('.btn-vender').forEach(btn => btn.addEventListener('click', async (e) => { e.stopPropagation(); const res = await fetch(`${API}/productos/vender/${btn.dataset.id}`, { method: 'PUT', headers: { Authorization: `Bearer ${token}` } }); const data = await res.json(); if (!res.ok) return alert(data.error || 'No se pudo vender'); alert('Venta registrada'); cargarProductos(); })); }
window.crearProducto = async function () { const body = { nombre: nombre.value.trim(), precio: Number(precio.value), stock: Number(stock.value), imagen: imagen.value.trim(), categoryId: Number(categoria.value) }; const res = await fetch(`${API}/productos`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(body) }); const data = await res.json(); if (!res.ok) return alert(data.error || 'Error al crear producto'); alert('Producto creado'); document.querySelectorAll('.form-card input').forEach(i => i.value = ''); cargarProductos(); };
formActualizar?.addEventListener('submit', async (e) => { e.preventDefault(); if (!idActualizar.value) return alert('Seleccioná un producto'); const body = { nombre: nombreActualizar.value.trim(), precio: Number(precioActualizar.value), stock: Number(stockActualizar.value), imagen: imagenActualizar.value.trim(), categoryId: Number(categoriaActualizar.value) }; const res = await fetch(`${API}/productos/${idActualizar.value}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(body) }); const data = await res.json(); if (!res.ok) return alert(data.error || 'Error al actualizar'); alert('Producto actualizado'); cargarProductos(); });
btnEliminar?.addEventListener('click', async () => { if (!idActualizar.value) return alert('Seleccioná un producto'); if (!confirm('¿Eliminar este producto?')) return; const res = await fetch(`${API}/productos/${idActualizar.value}`, { method: 'DELETE', headers: { Authorization: `Bearer ${token}` } }); const data = await res.json(); if (!res.ok) return alert(data.error || 'Error al eliminar'); alert('Producto eliminado'); formActualizar.reset(); cargarProductos(); });
cargarCategorias().then(cargarProductos);
