const API = "http://localhost:3000";
const user = JSON.parse(localStorage.getItem("user") || "null");
const token = localStorage.getItem("token");
if (!user || user.rol !== "superadmin") window.location.href = "/pages/login.html";
window.logout = function () { localStorage.removeItem("user"); localStorage.removeItem("token"); window.location.href = "/pages/login.html"; };
window.actualizarRol = async function(id) { const rol = document.getElementById(`rol-${id}`).value; const res = await fetch(`${API}/users/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ rol }) }); if (!res.ok) return alert('Error al actualizar rol'); cargarUsuarios(); };
window.eliminarUsuario = async function(id) { if (!confirm('¿Eliminar este usuario?')) return; const res = await fetch(`${API}/users/${id}`, { method: 'DELETE', headers: { Authorization: `Bearer ${token}` } }); if (!res.ok) return alert('Error al eliminar usuario'); cargarUsuarios(); };
async function cargarUsuarios() { const res = await fetch(`${API}/users`, { headers: { Authorization: `Bearer ${token}` } }); const usuarios = await res.json(); tablaUsuarios.innerHTML = usuarios.map(u => `<tr><td>${u.id}</td><td>${u.usuario}</td><td><select id="rol-${u.id}"><option value="cliente" ${u.rol==='cliente'?'selected':''}>Cliente</option><option value="admin" ${u.rol==='admin'?'selected':''}>Admin</option><option value="superadmin" ${u.rol==='superadmin'?'selected':''}>Superadmin</option></select></td><td class="table-actions"><button class="btn-save" onclick="actualizarRol(${u.id})">Guardar</button><button class="btn-delete" onclick="eliminarUsuario(${u.id})">Eliminar</button></td></tr>`).join(''); }
formUsuario?.addEventListener('submit', async (e) => { e.preventDefault(); const body = { usuario: usuario.value.trim(), password: password.value, rol: rol.value }; const res = await fetch(`${API}/users`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(body) }); const data = await res.json(); if (!res.ok) return alert(data.error || 'Error al crear usuario'); alert('Usuario creado'); e.target.reset(); cargarUsuarios(); });
cargarUsuarios();
